/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mines.douai.tp.spring.alejandra.valentin;

import org.mines.douai.tp.spring.alejandra.valentin.annotations.AnnotationQuoteMain;
import org.mines.douai.tp.spring.alejandra.valentin.purexml.QuoteMain;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
	
	// XML Config
	ApplicationContext applicationContext = new ClassPathXmlApplicationContext("application-context.xml");
	QuoteMain mainBean = applicationContext.getBean("quoteMain", QuoteMain.class);
	
	// Annotation Config
	ApplicationContext annotationApplicationContext = new ClassPathXmlApplicationContext("applicationAnnotation-context.xml");
	AnnotationQuoteMain annotationBean = (AnnotationQuoteMain) annotationApplicationContext.getBean("AnnotationQuoteMain");
	
	public void printMainBeanContent() {
		this.mainBean.initalizeQuoteMain();
		for (int i = 1; i < 4; i++) {
			this.mainBean.printMoneyAndParities();
		}
	}

	public void printAnnotationBeanContent() {
		this.annotationBean.initalizeQuoteMain();
		for (int i = 1; i < 4; i++) {
			this.annotationBean.printMoneyAndParities();
		}
	}
	public static void main(String[] args) {
		App app1 = new App();
		System.out.println("------------------ XML CONFIG ---------------------");
		app1.printMainBeanContent();
		System.out.println("------------------ Annotation CONFIG ---------------------");
		app1.printAnnotationBeanContent();

	}
}
