/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mines.douai.tp.spring.alejandra;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mines.douai.tp.spring.alejandra.valentin.App;
import org.mines.douai.tp.spring.alejandra.valentin.annotations.AnnotationQuoteBeanImpl;
import org.mines.douai.tp.spring.alejandra.valentin.annotations.AnnotationQuoteMain;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

class AppAnnotationsTest {
	ApplicationContext annotationApplicationContext = new ClassPathXmlApplicationContext("applicationAnnotation-context.xml");
    
    
    @Test
	public void should_quote_service_bean_be_injected() {
	AnnotationQuoteBeanImpl bean = (AnnotationQuoteBeanImpl) annotationApplicationContext.getBean("AnnotationQuoteBeanImpl");
	// Vérifie que le bean a bien été injecté, sinon le test echoué
	Assertions.assertNotNull(bean.getService());
	}
    
    @Test
    public void should_bitcoin_bean_be_injected() {
    	AnnotationQuoteMain bean = (AnnotationQuoteMain) annotationApplicationContext.getBean("AnnotationQuoteMain");
    	// Vérifie que le bean a bien été injecté, sinon le test echoué
    	Assertions.assertNotNull(bean.getBitcoinBean());
    }
    
    @Test
    public void should_litecoin_bean_be_injected() {
		AnnotationQuoteMain bean = annotationApplicationContext.getBean("AnnotationQuoteMain", AnnotationQuoteMain.class);
    	// Vérifie que le bean a bien été injecté, sinon le test echoué
    	Assertions.assertNotNull(bean.getLitecoinBean());
    }
    
    @Test
    public void should_namecoin_bean_be_injected() {
    	AnnotationQuoteMain bean = annotationApplicationContext.getBean("AnnotationQuoteMain", AnnotationQuoteMain.class);
    	// Vérifie que le bean a bien été injecté, sinon le test echoué
    	Assertions.assertNotNull(bean.getNamecoinBean());
    }
    
    @Test
    public void is_bitcoin_bean_name_injected() {
    	AnnotationQuoteMain bean = annotationApplicationContext.getBean("AnnotationQuoteMain", AnnotationQuoteMain.class);
    	bean.initalizeQuoteMain();
    // Vérifie que le bean a bien été injecté, sinon le test echoué
     Assertions.assertEquals(bean.getBitcoinBean().getName(), "Bitcoin");
    }
    
    @Test
    public void is_litecoin_bean_name_injected() {
    	AnnotationQuoteMain bean = annotationApplicationContext.getBean("AnnotationQuoteMain", AnnotationQuoteMain.class);
    	bean.initalizeQuoteMain();
    // Vérifie que le bean a bien été injecté, sinon le test echoué
     Assertions.assertEquals(bean.getLitecoinBean().getName(), "Litecoin");
     
     
    }
    
    @Test
    public void is_namecoin_bean_name_injected() {
    	AnnotationQuoteMain bean = annotationApplicationContext.getBean("AnnotationQuoteMain", AnnotationQuoteMain.class);
    	bean.initalizeQuoteMain();
    // Vérifie que le bean a bien été injecté, sinon le test echoué
     Assertions.assertEquals(bean.getNamecoinBean().getName(), "Namecoin");
    }
    
    
}
