/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mines.douai.tp.spring.alejandra;

import org.junit.jupiter.api.Test;
import org.mines.douai.tp.spring.alejandra.valentin.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
